// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/adrie/Desktop/GPCiclying/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/adrie/Desktop/GPCiclying/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('GroupCiclying', appParameters);
});
var entryPoint = require('c:/Users/adrie/Desktop/GPCiclying/index.js');